apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-list.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
