apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list.fullname" . }}-api
  labels:
    {{- include "todo-list.labels.api" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-list.selectorLabels.api" . | nindent 4 }}
