apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list.fullname" . }}-ui
  labels:
    {{- include "todo-list.labels.ui" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ui.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-list.selectorLabels.ui" . | nindent 4 }}
